### ISSUE TITLE
New section tool and possibility of exporting "the result" to obj

### ISSUE THREAD

**Issue by gmiguelr87** [cnr-isti-vclab/3DHOP#10]
First of all, thanks to the whole team.
3DHop is a fantastic tool!

I am relatively new to this whole world and I have some doubts:
- On the one hand, I read that you are going to publish a tutorial on how to create a more advanced section tool. I was wondering how I can do it now.
- On the other hand, I was also wondering if the sectioned 3D model I'm viewing can be exported to obj for example, and what the process would be like.

Thank you!!

**Comment by mcallieri** [comment]
Hi. 

yes, we plan to add some templates and tutorials on how to procedurally place the section plane in a specific position, and how to rotate the section plane, but we do not have an exact plan, and this can take a while.

for the other thing, unfortunately, this is not possible, and will never be possible. The section you see is just done in rendering, we simply stop drawing the object after a certain position. This means that the section is NOT calculated on the geometry. :(
This makes thing really fast, but the resulting cut-through section is just a visual data, without actual XYZ coordinates.

**Comment by gmiguelr87** [comment]
Hi @mcallieri ,

Thank you for your really quick response! It's very good and fast using the nxs format!
3DHop is really fantastic to visualize my models and analyze them (get coordinates, measures, etc), even it would be able to scale the models or change it reference system (or simulate it) thanks to translation and rotation internal functions.

I asked that because I was thinking about the possibility to add some editing tools, like a segment tool (for example if I want only a part of the model, or maybe to delete some "noise" in the model), in short, add a more extensive set of tools, including some for editing the model and exporting it to other formats.
