### ISSUE TITLE
Model without illumination on iPhone X and XR (latest version of 3DHop)

### ISSUE THREAD

**Issue by gmiguelr87** [cnr-isti-vclab/3DHOP#16]
Hello again!

I'm using the latest version of 3DHop (which is great), but I have a problem. With iPhone X and XR the 3D model looks totally black on both sides, however with iPhone 6 there is no such problem, not even in Safari for PC.

What could be the problem? How could I fix it?
Thank you very much in advance.

**Comment by potenziani** [comment]
Hi @gmiguelr87,
a few questions to better understand your problem:

- do you have issues in visualizing both Nexus and PLY files? 
- do you have issues in visualizing both compressed and uncompressed files (just if the problem happens with the Nexus format)? 
- do you have issues in visualizing both textured and color x vertex models? 
- do you have issues also in visualizing the different examples on our official website? 

Let us know, and thanks in advance

**Comment by gmiguelr87** [comment]
Hi @potenziani ,

Well, after studying the matter as much as I could, it was simply solved without doing anything after a week. I tried to do a thousand things, but finally I think it must have been some iOS update. It hasn't happened again, so it's not a 3DHop bug.
Yes, it really happened with some (not all) examples of the official website, it was really strange.
I consider the topic closed.

As always, thank you very much for everything!
