### ISSUE TITLE
Doubt/suggestion - 3D Map

### ISSUE THREAD

**Issue by gmiguelr87** [cnr-isti-vclab/3DHOP#21]
Hi again @potenziani 

First of all, I'm very impressed with the project, the more I use it, the more I like it!

I have different georeferenced 3D mesh models of lands, and I was wondering if it would be possible to integrate some layer like OpenStreetMap into the viewer. I have seen something very interesting in that sense, the Cesium library. Before going deeper into the subject, I would like you to give me your point of view, and if it would be possible for me to do so.

As always, infinite thanks!

**Comment by potenziani** [comment]
Hi @gmiguelr87,
once again, thanks for your appreciation!

3DHOP has not been specifically designed for handling maps/terrains, for this reason, by default, it doesn't provide 3D models georeferentiation or other specialized tools (in this sense, GIS-like applications, like for instance Cesium, could be the best option to meet your needs).

However, this not prevent you to develop your own tools or to adapt external resources to 3DHOP. 

For instance, these examples [[1]](http://mappegis.regione.emilia-romagna.it/gstatico/documenti/unesco/mappe_fe.html) [[2]](http://mappegis.regione.emilia-romagna.it/gstatico/documenti/unesco/lobi.html) show you different kinds of layers visualization for terrain 3D maps (not sure if this was what you meant with OpenStreetMap-like layers). In these cases several maps are visualized as different Nexus models, but in the next future we should be able to visualize multiple textures on the same multiresolution model (so, without the need to switch the visibility of different 3D models).

Moreover, several widgets often used in maps or terrain exploration has been successfully tested in 3DHOP, like for instance: a minimap for getting an overview plus detail visualization and driving the 3D navigation [[3]](http://vcg.isti.cnr.it/alchemy/viewer/index.html), or a compass for showing the 3D model position relatively to the geographic cardinal directions (unfortunately no public examples with this implementation are currently available).

I hope this can help. In any case, let us know if you need further clarifications.

**Comment by gmiguelr87** [comment]
Hi again @potenziani ,

Well, what I'd like to do with the openStreetMap layers is something different. I'll see if I can implement it and I'll tell you something.
Regarding the option to have multiple textures in the same multiresolution model is something I'm very interested in. Do you have any idea what date it might be available for? Or is it in some branch of development?

Thank you!!

**Comment by potenziani** [comment]
Hi @gmiguelr87 ,
unfortunately at the moment we have not a date for the release of this feature  (also, it is not available in any dev branch).
In the meanwhile, good luck with your implementation, and let us know if you do any progress with it!

**Comment by gmiguelr87** [comment]
Thank your very much @potenziani ,

I don't have the time I would like to be able to move forward with this idea, but I will do it step by step and if I succeed I will keep you informed!
