### ISSUE TITLE
Touch control 

### ISSUE THREAD

**Issue by DavidGilHidalgo** [cnr-isti-vclab/3DHOP#22]
Hi, I'm trying to access the code that controls tactile gestures on mobile devices.
I want to allow the 3D model to move if two fingers are used in the same direction.
I don't know if this function is done using JS or spiderGL.
Thanks again!

**Comment by potenziani** [comment]
Hi @DavidGilHidalgo ,

in 3DHOP the handling for touch gestures is implemented in the spidergl.js file (click 
[here](https://github.com/cnr-isti-vclab/3DHOP/files/3335091/spidergl.zip) to download the current spidergl version not minified).

In particular, take a look at these 5 functions: 
- _onTouchStart (line 16227);
- _onTouchEnd (line 16266);
- _onTouchMove (line 16321);
- _resolveTouchZoom (line 16387);
- _resolveTouchPan (line 16403);

... and let us know if you need further help!

**Comment by DavidGilHidalgo** [comment]
Hi @potenziani thank you so much for the quick response.
I'll take a look at spiderGL functions.
Great help always!
