### ISSUE TITLE
Deformed model when changing trackball position

### ISSUE THREAD

**Issue by gmiguelr87** [cnr-isti-vclab/3DHOP#24]
Hello again friends,

I'm working to automatically modify the trackball (the cameras) with setTrackballPosition function, so that a sequence of model views can be shown automatically. I'm calculating the positions and everything is fine except in one of them, in which the model is deformed (it's a house, and at that point it's practically flat, crushed, as if a giant stepped on it).
I can't understand exactly why it happens only at that point.

Any orientation will be welcome.
Thanks!

**Comment by gmiguelr87** [comment]
Hello again,

I'm sorry to have opened this issue, I don't know why I didn't notice before, but I had a 4x4 matrix value with a wrong sign. I close the issue, as I can not remove it.

Again, thank you for the impressive project, I'm delighted to enjoy it and the 3D world.

Best regards!

**Comment by gmiguelr87** [comment]
Hi @potenziani ,

Regarding this (playing with trackball), I'm trying to get some positions automatically (similar to animations but with trackballsphere).
I am having some complications due to the different possible rotation matrices, and it would be helpful for me to know what convention has been used for the construction of the trackball matrix.

Thank you very much in advance!

**Comment by potenziani** [comment]
Hi @gmiguelr87 
given the time that has passed, I'm not sure this answer is still required... 

Anyway, 3DHOP uses the "object in hand" metaphor: it works similarly like the hardware trackball
devices, allowing the user to define 3D roto translations using a 2D input space.

Actually, from your question I cannot understand if you are referring just to the sphere trackball, or if you are talking more in general. However, 3DHOP currently (version 4.2) provides 4 documented trackballs: turntable (default), pantilt, turntable_pan, sphere. The first three are quite similar (and allow camera animations), while the last one is a little bit different (and does not allow camera animations). 

To understand turntable, pantilt, and turntable_pan trackballs this figure can help:

![trackballs](https://user-images.githubusercontent.com/2982503/72539529-b6f91280-387f-11ea-96fb-f852a6cd43f8.jpg)

Basically the camera is located at P which is defined by theta, phi, and radius. You can rotate and move freely wherever you want by changing those three values. However, you always look at, and rotate around, the local origin of the sphere (actually, you are free to move this origin wherever we want in world space, but this is another story).

The three JavaScript files related to these trackballs contain:
- the "rotate", "pan" and "scale" functions (at the end of the files) that update the values of theta, phi, and radius;
- the "_computeMatrix" function (in the middle of the files) that calculates the 4X4 roto translation matrices.

Sphere trackball is instead implemented as a virtual trackball. To understand it, this figure can help:

![sphere](https://user-images.githubusercontent.com/2982503/72541675-3a683300-3883-11ea-99b5-44b05972903f.jpg)

Basically what you have to do in this case is to superimpose a hemisphere onto the viewport and then to orthographically project the mouse position (x,y,0) to this hemi-sphere (x,y,z). Now, if you want to rotate the camera from a point to another, you have to project both the previous mouse position (p1) and of the current position (p2). Once you have done that, you have to rotate the sphere from p1 to p2 by finding the proper rotation axis (calculated as cross-product between the p1 and the p2 vector) and angle (approximated as Euclidean norm or the rotation axis vector). Also in this case, a figure can help in understanding: 

![sphere1](https://user-images.githubusercontent.com/2982503/72542682-d47cab00-3884-11ea-9bc5-9dfb12bde56f.jpg)

The sphere trackball JavaScript file contains:
- the "rotate" function (at the end of the files) that update the values of the axis and angle of rotation ("pan" and "scale" functions are also present, but their calculations are more trivial);
- the "_computeMatrix" function (in the middle of the files) that calculates the 4X4 roto translation matrix.

Clearly, it is quite impossible to explain trackballs in detail in this venue, and sincerely I don't know if this is enough for clarifying your doubts... however, I hope you can benefit from it!
