### ISSUE TITLE
bump/normal etc

### ISSUE THREAD

**Issue by TJRL** [cnr-isti-vclab/3DHOP#30]
Hi again, I wondered whether it is in the pipeline to add additional image map capacities such as bump/normal/roughness/AO?

**Comment by potenziani** [comment]
Hi @TJRL  and sorry for the delay in the reply. 

Currently we are investigating the possibility to build a Nexus model using multiple textures/image maps. However, this is an idea still in the embryonic stage, so at the moment is not possible for us to provide you with a reliable time horizon.
