### ISSUE TITLE
sglHandleCanvas is not defined

### ISSUE THREAD

**Issue by felmab** [cnr-isti-vclab/3DHOP#34]
We use 3DHOP on a Drupal 7 website. I tried to upgrade the library to the latest release. When my page loads, I get the following error in console: ReferenceError: sglHandleCanvas is not defined (in presenter.js, line 43). I can replace sglHandleCanvas by SpiderGL.UserInterface.handleCanvas, but of course other errors arise later.

SpiderGL.openNamespace() does get called on line 20, however it does not really seem to do its job (and since spidergl.js is obfuscated, it is quite tricky to understand what happens inside)... Any help would be greatly appreciated.

**Comment by potenziani** [comment]
Hi @felmab 
could you provide me whit the version number of the 3DHOP package you are currently using (the one causing the problem) and, if you remember it, the version number of the 3DHOP package you used before (the one that worked).

Here you have the archive containing the current spidergl.js file not minified:

[spidergl.zip](https://github.com/cnr-isti-vclab/3DHOP/files/4348686/spidergl.zip)

**Comment by potenziani** [comment]
Hi again @felmab 
could you please try also this minified version (still latest DEV branch):

[spidergl.zip](https://github.com/cnr-isti-vclab/3DHOP/files/4349274/spidergl.zip)

Thanks, let me know

**Comment by felmab** [comment]
Thanks @potenziani. Both files work, and it made me realize this bug is entirely my fault: Drupal makes it difficult to include files that use `$` instead of `jQuery`, so I replaced all occurrences of the former with the latter using sed (which is a rather dirty solution, but the alternatives were not much cleaner)... I certainly should check the other files while I am at it. Sorry for bothering you.
