### ISSUE TITLE
Allow configurable selectors

### ISSUE THREAD

**Issue by felmab** [cnr-isti-vclab/3DHOP#37]
When we instantiate a Presenter object, we need to provide the ID of a `<canvas>` element. However, it looks like other selectors (like `#toolbar`) cannot be configured, which force us to alter 3DHOP sources if this ID already exists on a website. Ideally, we could provide options to control this.

**Comment by potenziani** [comment]
Hi @felmab

you're absolutely right ... This is an old 3DHOP problem, but the good news is that we are finally on it. In fact, in the next months 3DHOP will go through a renewal process, also aimed at solving this weakness.

So, stay tuned (and in the meanwhile remember to keep your code updated with the latest 3DHOP DEVELOPMENT version)!
