### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by ChrisSmiley** [cnr-isti-vclab/3DHOP#38]
Hi, 
I just wanted to let you know that our team have been helping out a bunch of open source projects by running security checking tools through some DevOps automation we setup.  We’ve found some items for you over at https://source-security.co.uk/51d233e9-37dc-447e-98f9-457ecafed57a/
Thanks, Chris

**Comment by mcallieri** [comment]
This is spam. 
Reported & blocked the user
